---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Ensure git is installed
  apt:
    name: git
    state: present

- name: Clone LightHouse repo
  git:
    repo: "https://github.com/VKCOM/lighthouse.git"
    dest: "{{ lighthouse_root_dir }}"
    version: master

- name: Configure Nginx
  template:
    src: lighthouse.conf.j2
    dest: /etc/nginx/sites-available/lighthouse
  notify: Reload Nginx

- name: Enable LightHouse site
  file:
    src: /etc/nginx/sites-available/lighthouse
    dest: /etc/nginx/sites-enabled/lighthouse
    state: link
    force: yes

- name: Disable default Nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
